version: '3.9'
services:
  pytorch_env:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    shm_size: 16g
    volumes:
      - .:/work
      - ${HOST_DATA_DIR}:/data
