version: '3.9'
services:
  pytorch_env:
    build:
      context: .
      args:
        USERNAME: user
        GROUPNAME: user
        UID: 1000
        GID: 1000
    tty: true
    stdin_open: true
    volumes:
      - .:/work
      - ${HOST_DATA_DIR}:/data
    shm_size: 16g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
